# Generated by Django 4.2.15 on 2025-10-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_queue', '0002_menuitem_demand_quantity_demand_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
