# Generated by Django 4.2.15 on 2025-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_queue', '0003_remove_demand_food_item_remove_demand_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='expected_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=10),
        ),
    ]
