# Generated by Django 4.2.15 on 2025-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_queue', '0004_demand_completed_at_demand_expected_completion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='priority',
        ),
        migrations.AddField(
            model_name='demand',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='room_or_table',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
